/**
 * ContaCorrenteSOAPImpl.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package br.com.bradseg.bucb.servicos.model.service;

public interface ContaCorrenteSOAPImpl extends java.rmi.Remote {
    public br.com.bradseg.bucb.servicos.model.vo.IdentificarCorrentistaSegmentoEmpresaSaidaVO identificarCorrentistaSegmentoEmpresa(java.lang.String ipCliente, java.lang.String userID, long agencia, long cpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrenteVO consultarCorrentistasPorAgenciaContaCorrente(java.lang.String ipCliente, java.lang.String userID, int codigoAgencia, long numeroContaCorrente) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrenteFuncionarioIdBucVO obterContaCorrentePorIdBuc(java.lang.String ipCliente, java.lang.String userID, long idBuc) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrenteVO consultarDadosCorrentista(java.lang.String ipCliente, java.lang.String userID, long cpfCnpj, int codigoAgencia, long numeroContaCorrente) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ValidarDadosFuncionarioSinergiaSaidaVO validarDadosFuncionarioSinergia(br.com.bradseg.bucb.servicos.model.vo.ValidarDadosFuncionarioSinergiaEntradaVO validarDadosFuncionarioSinergiaEntradaVO) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListarSubsegmentoRencRespectivasAgenciasSaidaWsVO listarSubsegmentoRencRespectivasAgencias(long cpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public java.lang.String validarDadosContaCorrente(java.lang.String ipCliente, java.lang.String userID, br.com.bradseg.bucb.servicos.model.vo.ValidarDadosContaCorrenteVO validarDadosVO) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ValidarDadosFuncionarioVO validarDadosFuncionario(java.lang.String ipCliente, java.lang.String userID, long matricula, long agencia, long conta) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListarSegmentacaoProdutoClienteSaidaVO listarHistoricoSegmentacaoProdutoCliente(long cpfCnpj, long agencia, long data) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrentePorCPFCNPJVO[] listarCorrentistasPorCpfCnpj(int tpConta, long cpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public boolean validarDVContaCorrente(java.lang.String ipCliente, java.lang.String userID, long cpfCnpj, int codigoAgencia, long numeroContaCorrente, java.lang.String dvContaCorrente) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListarAgenciaPorCpfCnpjSaidaVO listarAgenciaPorCpfCnpj(long cpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListaContaCorrenteFuncionarioWsVO obterContaCorrenteFuncionarioPorIDBuc(java.lang.String ipCliente, java.lang.String userID, long idBuc) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.PessoaContaCorrenteVO obterDadosCorrentistaIDCRRTT(long idCrrtt) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListarCorrentistasPorAgCcSaidaVO listarCorrentistasPorAgCc(br.com.bradseg.bucb.servicos.model.vo.ListarCorrentistasPorAgCcVO listarCorrentistasPorAgCcVO) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.PessoaContaCorrenteVO[] consultarMeioContatoPessoaContaCorrente(java.lang.String ipCliente, java.lang.String userID, br.com.bradseg.bucb.servicos.model.vo.PessoaContaCorrenteEntradaVO pessoaContaCorrente) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrenteCpfVO[] consultarContaCorrentePorCPF(java.lang.String ipCliente, java.lang.String userID, long cpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListarSegmentacaoProdutoClienteSaidaVO listarSegmentacaoProdutoCliente(long cpfCnpj, long agencia) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ValidarDVFuncionarioSaidaVO validarContaCorrente(java.lang.String ipCliente, java.lang.String userID, br.com.bradseg.bucb.servicos.model.vo.ValidarDVFuncionarioEntradaVO entrada) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ListarSegmentacoesPOBJeRENCSaidaVO listarSegmentacoesPOBJeRENC(java.lang.String ipCliente, java.lang.String userID, long cpfCnpj, long agencia) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrenteCpfVO[] obterDadosBaseContaCorrentePorCPF(long tpConta, long cpf) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.ContaCorrenteVO[] consultarContaCorrentePorCPFCNPJ(java.lang.String ipCliente, java.lang.String userID, long cpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public br.com.bradseg.bucb.servicos.model.vo.IdentificarPessoaCCSaidaVO identificarPessoa(br.com.bradseg.bucb.servicos.model.vo.IdentificarPessoaCCEntradaVO identificarPessoaCCEntradaVO) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
    public long obterIDBucPorContaCorrenteCpfCnpj(br.com.bradseg.bucb.servicos.model.vo.IDBucPorContaCorrenteCpfCnpjVO IDBucPorContaCorrenteCpfCnpj) throws java.rmi.RemoteException, br.com.bradseg.bucb.servicos.model.exception.WebServiceBusinessException, br.com.bradseg.bucb.servicos.model.exception.WebServiceIntegrationException;
}
